### ISSUE TITLE
希望有模糊匹配功能, 或者单词输错有智能提示 (如图)

### ISSUE THREAD

**Issue by ssthouse** [RogerZZZZZ/dictionary-cli#1]
![selection_478](https://user-images.githubusercontent.com/10973821/48126908-5fdfd100-e2bd-11e8-9325-dd9c9311969d.png)

**Comment by RogerZZZZZ** [comment]
我试试- - 等我

**Comment by RogerZZZZZ** [comment]
@ssthouse 基本功能差不多写完了 你可以试试 哈哈哈 我明天npm publish一下~

**Comment by RogerZZZZZ** [comment]
@ssthouse 完工
